# Generated by Django 5.1 on 2024-08-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_customuser_address_customuser_bio_customuser_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='conversation_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
